zone = "المنطقة"
service = "الخدمة"
identifier = "المعرف"
filter_by = "بحث حسب المنطقة أو المعرف"

Services = "الخدمات"

manual_setup = "إعداد يدوي"
remove_rule = "إزالة القاعدة"

manual_setup_description_1 = "أنشئ قاعدة حظر صادرة لنطاقات العناوين هذه باستخدام بروتوكول (UDP) والمنافذ المحددة."
manual_setup_description_2 = "إذا كان جدار الحماية يدعم ذلك، فقم بتطبيق القاعدة على أوفرواتش فقط."

copy_ip_ranges = "نسخ نطاقات العناوين"
copy_ports = "نسخ المنافذ"

load_google_error = "حدث خطأ اثناء استرداد المناطق من جوجل"
load_amazon_error = "حدث خطأ اثناء استرداد المناطق من أمازون"

save_error = "حدث خطأ أثناء حفظ المناطق المحددة إلى الملف"

rule_applied = "تم تطبيق القاعدة بنجاح"
relaunch_game = "إذا كانت اللعبة قيد التشغيل يجب عليك إعادة تشغيلها"
rule_removed = "تم إزالة القاعدة بنجاح"

executable_not_found = "لم يتم العثور على ملف اللعبة"
select_correct_location = "تأكد من تحديد موقع الملف الصحيح"
no_regions_selected = "لم يتم تحديد أي منطقة"
apply_rule_error = "حدث خطأ أثناء تطبيق القاعدة"
remove_rule_error = "حدث خطأ أثناء إزالة القاعدة"

copy_ranges_error = "حدث خطأ أثناء نسخ نطاقات العناوين"
copy_ports_error = "حدث خطأ أثناء نسخ المنافذ"

copied_ranges = "تم نسخ نطاقات العناوين"
copied_ports = "تم نسخ المنافذ"