zone = "المنطقة"
service = "الخدمة"
identifier = "المعرف"
filter_by = "بحث حسب المنطقة أو المعرف"

Services = "الخدمات"

remove_rule = "إزالة القاعدة"

load_google_error = "حدث خطأ اثناء استرداد المناطق من جوجل"
load_amazon_error = "حدث خطأ اثناء استرداد المناطق من أمازون"

save_error = "حدث خطأ أثناء حفظ المناطق المحددة إلى الملف"

rule_applied = "تم تطبيق القاعدة بنجاح"
relaunch_game = "إذا كانت اللعبة قيد التشغيل يجب عليك إعادة تشغيلها"
rule_removed = "تم إزالة القاعدة بنجاح"

executable_not_found = "لم يتم العثور على ملف اللعبة"
select_correct_location = "تأكد من تحديد موقع الملف الصحيح"
no_regions_selected = "لم يتم تحديد أي منطقة"
apply_rule_error = "حدث خطأ أثناء تطبيق القاعدة"
remove_rule_error = "حدث خطأ أثناء إزالة القاعدة"